(()=>{
  const REPORTS_KEY='wd_reports_v1';
  let pendingPhoto=null;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function injectStyles(){if(document.getElementById('wd-report-photo-style'))return;const s=document.createElement('style');s.id='wd-report-photo-style';s.textContent=`.report-photo-box{margin:12px 0;padding:12px;border:1px solid rgba(59,36,24,.12);border-radius:16px;background:#fff}.report-photo-box b{display:block;font-size:12px;margin-bottom:7px}.report-photo-pick{display:flex;align-items:center;justify-content:center;gap:8px;min-height:48px;border:1.5px dashed #cdbfae;border-radius:13px;font-weight:900;cursor:pointer}.report-photo-pick input{position:absolute;opacity:0;width:1px;height:1px}.report-photo-preview{display:none;position:relative;margin-top:10px}.report-photo-preview.show{display:block}.report-photo-preview img{display:block;width:100%;max-height:220px;object-fit:cover;border-radius:13px}.report-photo-remove{position:absolute;top:8px;right:8px;min-width:44px;min-height:44px;border:0;border-radius:999px;background:rgba(255,255,255,.94);font-size:22px}.report-photo-note{margin:7px 0 0;color:#71655c;font-size:10px;line-height:1.35}.report-detail-photo{width:100%;max-height:320px;object-fit:cover;border-radius:16px;margin:8px 0 12px}`;document.head.appendChild(s)}

  function injectUi(){const details=document.getElementById('reportDetails');if(!details||document.getElementById('reportPhotoBox'))return;const box=document.createElement('div');box.id='reportPhotoBox';box.className='report-photo-box';box.innerHTML=`<b>Foto toevoegen <span style="font-weight:500">(optioneel)</span></b><label class="report-photo-pick">📷 Foto kiezen of maken<input id="reportPhotoInput" type="file" accept="image/*" capture="environment"></label><div id="reportPhotoPreview" class="report-photo-preview"><img id="reportPhotoImage" alt="Voorbeeld van je melding"><button id="reportPhotoRemove" class="report-photo-remove" type="button" aria-label="Foto verwijderen">×</button></div><p class="report-photo-note">De foto hoort alleen bij deze melding. Deel geen herkenbare personen of privégegevens.</p>`;const loc=details.querySelector('.location-card');loc?.insertAdjacentElement('beforebegin',box);const input=document.getElementById('reportPhotoInput');input?.addEventListener('change',onPhoto);document.getElementById('reportPhotoRemove')?.addEventListener('click',clearPhoto)}

  function clearPhoto(){pendingPhoto=null;const input=document.getElementById('reportPhotoInput');if(input)input.value='';document.getElementById('reportPhotoPreview')?.classList.remove('show');const img=document.getElementById('reportPhotoImage');if(img)img.removeAttribute('src')}

  async function fileToJpeg(file){if(!file?.type?.startsWith('image/'))throw new Error('not-image');if(file.size>12*1024*1024)throw new Error('too-large');const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url});const max=1280,scale=Math.min(1,max/Math.max(img.naturalWidth||1,img.naturalHeight||1));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.82)}finally{URL.revokeObjectURL(url)}}

  async function onPhoto(e){const file=e.target.files?.[0];if(!file){clearPhoto();return}try{pendingPhoto=await fileToJpeg(file);const img=document.getElementById('reportPhotoImage');if(img)img.src=pendingPhoto;document.getElementById('reportPhotoPreview')?.classList.add('show');window.toast?.('Foto toegevoegd aan je melding')}catch(err){console.warn(err);clearPhoto();window.toast?.(err?.message==='too-large'?'Deze foto is te groot. Kies een foto kleiner dan 12 MB.':'Deze foto kon niet worden gebruikt. Kies een andere afbeelding.')}}

  function installSaveHook(){if(window.saveJSON?.__wdReportPhoto)return;const base=window.saveJSON;if(typeof base!=='function')return;const wrapped=function(key,value){if(key===REPORTS_KEY&&Array.isArray(value)&&pendingPhoto&&document.getElementById('reportDialog')?.open&&value.length){const last=value[value.length-1];if(last&&typeof last==='object'&&!last.photoDataUrl)last.photoDataUrl=pendingPhoto}return base(key,value)};wrapped.__wdReportPhoto=true;window.saveJSON=wrapped}

  function installDetailHook(){const base=window.openReportDetail;if(typeof base!=='function'||base.__wdReportPhoto)return;const wrapped=function(report){base(report);const content=document.getElementById('detailContent');if(!content||!report?.photoDataUrl)return;const img=document.createElement('img');img.className='report-detail-photo';img.src=report.photoDataUrl;img.alt=`Foto bij melding ${esc(report.subtype||report.type||'')}`;const body=content.querySelector('.detail-body');(body||content.firstChild)?.insertAdjacentElement?.('beforebegin',img)};wrapped.__wdReportPhoto=true;window.openReportDetail=wrapped}

  function resetOnOpen(){document.getElementById('reportFab')?.addEventListener('click',()=>setTimeout(clearPhoto,0));document.getElementById('mapPlusBtn')?.addEventListener('click',()=>setTimeout(clearPhoto,0));document.getElementById('homeReport')?.addEventListener('click',()=>setTimeout(clearPhoto,0))}
  function boot(){injectStyles();injectUi();installSaveHook();installDetailHook();resetOnOpen();const obs=new MutationObserver(()=>{injectUi();installSaveHook();installDetailHook()});obs.observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,80),{once:true});else setTimeout(boot,80);
})();