const PREFIX='whatsup-dog:'+self.registration.scope+':';
const CACHE=PREFIX+'v49';
const CORE=['./vendor/leaflet/leaflet.js','./vendor/leaflet/leaflet.css','./vendor/leaflet/images/layers.png','./vendor/leaflet/images/layers-2x.png','./vendor/leaflet/images/marker-icon.png','./icon-192.png','./icon-512.png','./','./index.html','./styles.css?v=6','./design-system.css?v=1.9.1','./production-feed.css?v=1','./paw-wheel.css?v=1','./maintenance-ui.css?v=1','./account-login.css?v=1','./quick-report-wheel.css?v=1','./v2-layout.css?v=1','./breed.css?v=2','./home.css?v=5','./app.js?v=7','./production-feed.js?v=1','./production-alerts.js?v=1','./paw-wheel.js?v=1','./maintenance-ui.js?v=1','./account-login.js?v=1','./quick-report-wheel.js?v=1','./official-areas.js?v=9','./home.js?v=5','./smart-report.css?v=3','./smart-report-v3.js?v=3','./backend-config.js?v=4','./community-backend.js?v=2','./species-context.js?v=1.9.1','./community-ui-bridge.js?v=1','./dialog-ui.js?v=3','./profile-ui.js?v=1','./directory-ui.js?v=1.9.0','./community-tools.js?v=1.9.1','./ui-hotfix-1.6.2.js?v=2','./version.js?v=1.9.1','./mobile-ui.js?v=1.9.1','./report-lifecycle.js?v=1.9.1','./report-photo.js?v=1.7.0','./breed-catalog.js?v=2','./install-guide.js?v=1.9.1','./manifest.webmanifest','./icon.svg','./waldo-mark.png','./data/nijkerk-losloopgebieden.geojson'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(PREFIX)&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url);
  if(url.origin!==location.origin){event.respondWith(fetch(event.request));return}
  if(event.request.mode==='navigate'){event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{if(response.ok){const clone=response.clone();caches.open(CACHE).then(cache=>cache.put('./index.html',clone));}return response}).catch(()=>caches.match('./index.html')));return}
  event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{if(response.ok){const clone=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,clone));}return response}).catch(()=>caches.match(event.request)))
});
self.addEventListener('push',event=>{let payload={};try{payload=event.data?.json()||{}}catch{}event.waitUntil(self.registration.showNotification('Whatsup dog',{body:String(payload.body||'Er is een nieuwe melding.').slice(0,180),icon:'./icon-192.png',tag:'whatsup-dog'}))});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(self.clients.openWindow(self.registration.scope))});
