import fs from 'node:fs';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';

const read=p=>fs.readFileSync(p,'utf8');
const appSource=read('app.js');
const smartSource=read('smart-report-v3.js');
const indexSource=read('index.html');
const breedSource=read('breed-catalog.js');
const lifecycleSource=read('report-lifecycle.js');
const backendConfigSource=read('backend-config.js');
const versionSource=read('version.js');
const speciesSource=read('species-context.js');
const designSource=read('design-system.css');
const lifecycleMigration=read('supabase/migrations/20260913000100_report_lifecycle.sql');
const lifecycleRecoveryMigration=read('supabase/migrations/20260915000100_reassert_report_lifecycle.sql');
const directoryRecoveryMigration=read('supabase/migrations/20260915000200_reassert_profile_directory.sql');
const version=versionSource.match(/version:'(\d+\.\d+\.\d+)'/)?.[1];
assert.ok(version,'Central SemVer version missing');
assert.match(speciesSource,/wd_profile_v1/,'Species context must use the persisted profile');
assert.match(speciesSource,/mode-cat/,'CAT context missing');
assert.match(speciesSource,/mode-both/,'BOTH context missing');
assert.match(designSource,/--surface-canvas/,'Semantic design tokens missing');

assert.equal((appSource.match(/function deleteReport\(/g)||[]).length,1,'Duplicate deleteReport handler');
assert.match(appSource,/id="resolveReport"[\s\S]*id="deleteReport"/,'Point detail actions missing');
assert.match(appSource,/el\('resolveReport'\)\.onclick=\(\)=>markReportResolved\(r\)/,'Point resolve handler missing');
assert.match(appSource,/el\('deleteReport'\)\.onclick=\(\)=>deleteReport\(r\)/,'Point delete handler missing');
assert.match(smartSource,/id="resolveReport"[\s\S]*id="deleteReport"/,'Area detail actions missing');
assert.match(smartSource,/\$\('resolveReport'\)\.onclick=\(\)=>markReportResolved\(r\)/,'Area resolve handler missing');
assert.match(smartSource,/\$\('deleteReport'\)\.onclick=\(\)=>deleteReport\(r\)/,'Area delete handler missing');
assert.match(smartSource,/selectedReportType==='lost'&&!selectedLostKind/,'Enhanced report flow must require lost/found choice');
assert.match(smartSource,/const subtype=selectedReportType==='lost'/,'Enhanced report flow must preserve lost/found subtype');
assert.match(smartSource,/\$\('mapPlusBtn'\)\?\.addEventListener\('click',resetOnOpen\)/,'Map quick-add must reset enhanced report state');
assert.match(appSource,/hiddenReports:'wd_hidden_reports_v1'/,'Hidden report storage missing');


const productionFeed=read('production-feed.js');
assert.match(indexSource,/id="view-feed"/,'Production public feed view missing');
assert.match(indexSource,/production-feed\.js\?v=1/,'Production public feed script missing');
assert.match(indexSource,/production-feed\.css\?v=1/,'Production public feed stylesheet missing');
assert.doesNotMatch(indexSource,/id="pushDemo"|Test een melding/,'Demo UI must not be shipped');
assert.match(indexSource,/id="view-chat"/,'Real private and group chat screen must ship');
assert.doesNotMatch(appSource,/function setupChat\(|setupChat\(\)|pushDemo/,'Demo handlers must not be shipped');
assert.match(productionFeed,/r\._remote===true/,'Public feed may show only server-confirmed reports');
assert.match(productionFeed,/dataset\.community==='community-aan'/,'Public feed must fail closed when backend is unavailable');
assert.match(read('sw.js'),/production-feed\.js\?v=1/,'Offline shell must include production feed');

const maintenanceSource=read('maintenance-ui.js');
const maintenanceGate=read('supabase/migrations/20260924000100_moderator_ui_gate.sql');
assert.doesNotMatch(indexSource,/paw-wheel\.js\?v=1/,'Obstructive side wheel must be removed');
assert.doesNotMatch(indexSource,/paw-wheel\.css\?v=1/,'Side wheel stylesheet must not ship');
assert.match(indexSource,/maintenance-ui\.js\?v=1/,'Maintenance UI missing from app');
assert.match(maintenanceSource,/rpc\('is_report_moderator'\)/,'Maintenance must verify role on the server');
assert.match(maintenanceSource,/rpc\('moderate_report'/,'Maintenance must use trusted moderation RPC');
assert.match(maintenanceGate,/security definer/,'Maintenance role gate must be enforced on the server');
assert.match(maintenanceGate,/revoke all on function public\.is_report_moderator/,'Moderator capability must not be public');

const speciesMigration=read('supabase/migrations/20260924000200_report_species.sql');
assert.match(speciesMigration,/add column if not exists species/,'Shared reports must preserve species in the database');
assert.match(productionFeed,/speciesMode\(\)/,'Public feed must use existing species preference');
assert.match(read('community-backend.js'),/species:row\.species/,'Shared reports must preserve remote species');

assert.doesNotMatch(appSource,/id="confirmReport"|id="thankReport"/,'Unverified point confirmation actions must not ship');
assert.doesNotMatch(smartSource,/id="confirmReport"|id="thankReport"/,'Unverified polygon confirmation actions must not ship');
assert.match(appSource,/const canManage=!r\._remote/,'Only owner can manage point report');
assert.match(smartSource,/const canManage=!r\._remote/,'Only owner can manage area report');
assert.match(productionFeed,/async function loadOlder\(\)/,'Public feed needs pagination beyond initial reports');
assert.match(productionFeed,/limit\(100\)/,'Pagination must be bounded');
assert.match(indexSource,/production-alerts\.js\?v=1/,'Production alert preferences must be functional');
assert.match(read('production-alerts.js'),/wd_alert_preferences_v1/,'Alert preferences must persist');
assert.doesNotMatch(indexSource,/id="clearReports"|id="pushDemo"/,'No inert mass-clear or test notification controls');
const loginSource=read('account-login.js');
assert.match(indexSource,/account-login\.js\?v=1/,'Accessible account login missing from profile');
assert.match(indexSource,/account-login\.css\?v=1/,'Login design stylesheet missing');
assert.match(read('sw.js'),/account-login\.js\?v=1/,'Login must be included in the offline app shell');
assert.match(loginSource,/signInWithPassword/,'Password sign-in missing');
assert.match(loginSource,/shouldCreateUser:false/,'Magic link must never silently create a new account');
const signupSource=read('account-onboarding.js');
assert.match(indexSource,/account-onboarding\.js\?v=1/,'Registration and profile editor must be included in the app');
assert.match(read('sw.js'),/account-onboarding\.js\?v=1/,'Member account setup must ship in the offline shell');
assert.match(signupSource,/auth\.signUp/,'Password account creation must be backed by Supabase Auth');
assert.match(signupSource,/shouldCreateUser:true/,'Passwordless signup must be an explicit separate option');
assert.match(signupSource,/resetPasswordForEmail/,'Account holders need a password recovery flow');
assert.match(signupSource,/auth\.updateUser/,'Users must be able to save a new password and pet preference');
assert.match(signupSource,/from\('profiles'\)\.upsert/,'Profile completion must persist under the authenticated account');
assert.match(signupSource,/preview\|\|!verified\(\)/,'Profile mutation must not be available to guests or preview');
assert.match(loginSource,/form\.hidden=verified\|\|preview/,'Preview must hide real credential inputs');
assert.match(loginSource,/id='wdAccountRegister'/,'Signup needs a dedicated, clearly labeled control');
assert.match(loginSource,/auth\.signOut/,'Account logout missing');
assert.match(read('community-backend.js'),/detectSessionInUrl:true/,'Magic-link callback sessions must be recognized');
assert.match(read('community-backend.js'),/wd:auth-changed/,'Shared backend must react to account changes');
assert.match(read('community-backend.js'),/report\._shareIntent!==true/,'Legacy reports must not enter the sharing queue');
assert.match(appSource,/_shareIntent:true/,'New point reports must record explicit sharing intent');
assert.match(smartSource,/_shareIntent:true/,'New area reports must record explicit sharing intent');

const quickWheel=read('quick-report-wheel.js');
const quickStyles=read('quick-report-wheel.css');
assert.match(indexSource,/quick-report-wheel\.js\?v=2/,'Thumb reporting wheel must ship');
assert.match(indexSource,/v2-layout\.css\?v=1/,'Approved 2.0 visual system must ship');
assert.match(quickWheel,/wd:quick-report-start/,'Quick category selection must trigger location prefill');
assert.match(quickWheel,/wd-quick-report/,'A real thumb-sized report control is required');
assert.match(quickStyles,/\.wd-wheel-disc/,'Quick reporting must show six actual categories');
assert.match(read('smart-report-v3.js'),/getCurrentPosition/,'Quick reports must use real device GPS');
assert.match(read('smart-report-v3.js'),/quickGpsPending/,'Quick reporting must wait for location result');
assert.match(read('smart-report-v3.js'),/We gokken je locatie niet/,'GPS failure must not silently publish map center');
assert.match(read('smart-report-v3.js'),/reportCameraV2/,'Camera capture must remain available');
assert.match(read('smart-report-v3.js'),/reportPhotoV2/,'Gallery upload must remain available');
assert.match(read('sw.js'),/quick-report-wheel\.js\?v=2/,'Offline cache must contain thumb reporting UI');

const chatSource=read('community-chat.js');
const groupMigration=read('supabase/migrations/20260924000300_verified_group_chat.sql');
assert.match(indexSource,/community-chat\.js\?v=1/,'Real chat UI must ship');
assert.match(indexSource,/data-view="chat"/,'Chat must be in the primary navigation');
assert.match(chatSource,/chat_messages/,'Chat must load actual member-only messages');
assert.match(chatSource,/start_private_chat/,'Private conversations must be backed by the server');
assert.match(chatSource,/start_group_chat/,'Groups must be backed by the server');
assert.match(chatSource,/isPreview\(\)/,'Preview cannot send chat messages');
assert.match(groupMigration,/Verified account required/,'Guest users must not create conversations');
assert.match(groupMigration,/Only distinct, discoverable members/,'Group invites require opt-in profiles');
assert.match(groupMigration,/reports_type_check/,'Other category must be accepted by the backend');
assert.match(quickWheel,/wdWheelDangerOptions/,'Danger must open a short dedicated submenu');
assert.match(quickWheel,/data-quick-type|dataset\.quickType/,'The six report options must be concrete controls');
assert.doesNotMatch(indexSource,/id="pawWheel"/,'No second side navigation wheel');

const directory=read('directory-ui.js');
const directoryMigration=read('supabase/migrations/20260924000400_profile_directory_hosted.sql');
const visibilityGuard=read('supabase/migrations/20260924000500_profile_visibility_guard.sql');
assert.match(directory,/set_profile_discoverability/,'Findability must use the trusted RPC');
assert.match(directory,/!verified\(\)/,'Anonymous visitors may not opt in');
assert.match(directory,/__WD_PREVIEW__/,'Preview cannot mutate real profile visibility');
assert.match(directory,/discoverable/,'Findability must be verified against the persisted server value');
assert.match(directoryMigration,/list_discoverable_profiles/,'Only opt-in profile fields may be returned');
assert.match(visibilityGuard,/enforce_verified_profile_visibility/,'Anonymous users must not bypass verified opt-in with direct writes');

const previewGuard=read('preview-guard.js');
const previewBuilder=read('scripts/build-preview.mjs');
assert.match(previewGuard,/__wdPreviewStorage/,'Preview must isolate browser data');
assert.match(previewGuard,/PREVIEW_READ_ONLY/,'Preview must refuse changes to hosted Supabase');
assert.match(previewGuard,/wdPreviewBanner/,'Preview must visibly identify itself');
assert.match(previewBuilder,/preview-guard\.js/,'Preview build must load read-only guard before app scripts');

const backendSource=read('community-backend.js');
assert.match(backendSource,/storageKey:window\.__WD_PREVIEW__/,'Preview must isolate Supabase Auth storage');
assert.match(backendSource,/wd_hidden_reports_v1/,'Remote hidden report filter missing');
assert.match(backendSource,/hiddenIds\.has\(row\.id\)/,'Remote refresh does not honor hidden reports');
assert.match(backendConfigSource,new RegExp(`report-lifecycle\\.js\\?v=${version.replaceAll('.','\\.')}`),'Persistent report lifecycle controller is not release-versioned');
assert.match(lifecycleSource,/set_own_report_status/,'Report lifecycle must persist owner status to Supabase');
assert.match(lifecycleSource,/LEGACY_CUTOFF/,'Legacy pre-release report cleanup missing');
assert.match(lifecycleSource,/wd_shared_report_queue_v1/,'Deleting an unsynced report must clear the sync queue');
assert.match(lifecycleSource,/Voor iedereen verwijderen lukt tijdelijk niet/,'Remote delete fallback must be truthful');
assert.match(lifecycleMigration,/create or replace function public\.set_own_report_status/,'Owner report lifecycle RPC missing');
assert.match(lifecycleMigration,/user_id=\(select auth\.uid\(\)\)/,'Lifecycle RPC must be owner-scoped');
assert.match(lifecycleRecoveryMigration,/create or replace function public\.set_own_report_status/,'Recovery migration must reassert lifecycle RPC');
assert.match(lifecycleRecoveryMigration,/17bfd990-6e69-4861-be8d-1ecf6b7adea4/,'Exact failed live E2E fixture cleanup missing');
assert.doesNotMatch(lifecycleRecoveryMigration,/delete\s+from|truncate\s|drop\s+table/i,'Recovery migration must not use broad destructive cleanup');
assert.match(directoryRecoveryMigration,/add column if not exists discoverable boolean/,'Directory recovery must reassert the opt-in column');
assert.match(directoryRecoveryMigration,/alter column discoverable set default false/,'Directory recovery must enforce privacy-safe opt-in default');
assert.match(directoryRecoveryMigration,/alter column discoverable set not null/,'Directory recovery must reject ambiguous opt-in state');
assert.match(directoryRecoveryMigration,/create or replace function public\.list_discoverable_profiles/,'Directory recovery must reassert the public directory RPC');
assert.match(directoryRecoveryMigration,/create or replace function public\.start_private_chat/,'Directory recovery must reassert the private chat RPC');

assert.equal((indexSource.match(/breed-catalog\.js/g)||[]).length,1,'Exactly one breed catalog must be loaded');
assert.doesNotMatch(indexSource,/breed-catalog-expanded\.js|breed-custom\.js|breed-custom\.css/,'Legacy breed picker assets still referenced');
assert.match(indexSource,/breed-catalog\.js\?v=2/,'Breed catalog cache-busting version missing');
assert.match(indexSource,/breed\.css\?v=2/,'Breed styles cache-busting version missing');
assert.match(indexSource,/smart-report\.css\?v=3/,'Enhanced report styles are not wired into frontend');
assert.match(indexSource,/smart-report-v3\.js\?v=3/,'Enhanced report controller is not wired into frontend');
assert.match(indexSource,/backend-config\.js\?v=4/,'Backend config is not wired into frontend');
assert.match(indexSource,/community-backend\.js\?v=2/,'Community backend is not wired into frontend');

const breedContext={window:{},document:{getElementById:()=>null}};
vm.runInNewContext(breedSource,breedContext);
const breedCatalog=breedContext.window.WHATSUP_DOG_BREEDS;
assert.ok(Array.isArray(breedCatalog),'Breed catalog export missing');
assert.ok(breedCatalog.length>=400,'Breed catalog unexpectedly small');
const breedNames=Array.from(breedCatalog,x=>String(x.name));
const sortedBreedNames=[...breedNames].sort(new Intl.Collator('nl',{sensitivity:'base',numeric:true}).compare);
assert.deepEqual(breedNames,sortedBreedNames,'Breed catalog is not alphabetical');
assert.equal(new Set(breedNames).size,breedNames.length,'Duplicate breed names');
const stabij=Array.from(breedCatalog).find(x=>x.name==='Stabijhoun (Friese Stabij)');
assert.ok(stabij,'Stabijhoun / Friese Stabij missing');
assert.ok(Array.from(stabij.aliases).includes('Stabijhoun'),'Stabijhoun alias missing');
assert.ok(Array.from(stabij.aliases).includes('Friese Stabij'),'Friese Stabij alias missing');
assert.ok(stabij.popular,'Stabijhoun should be marked popular');
assert.ok(Array.from(breedCatalog).find(x=>x.name==='Labrador Retriever')?.popular,'Popular breed marker missing');
assert.ok(Array.from(breedCatalog).find(x=>x.name==='Australian Shepherd')?.popular,'Official popular breed marker missing');

for(const f of fs.readdirSync('.').filter(f=>f.endsWith('.js')))execFileSync(process.execPath,['--check',f]);
const manifest=JSON.parse(read('manifest.webmanifest'));
assert.equal(manifest.scope,'./');
assert.equal(manifest.start_url,'./');
const geo=JSON.parse(read('data/nijkerk-losloopgebieden.geojson'));
assert.equal(geo.features.length,20);
for(const f of geo.features)assert.ok(['Polygon','MultiPolygon'].includes(f.geometry.type));

const events={};const deleted=[];let core=[];
const context={self:{registration:{scope:'https://example.test/whatsup-dog/'},addEventListener:(k,f)=>events[k]=f,skipWaiting:async()=>{},clients:{claim:async()=>{}}},caches:{open:async()=>({addAll:async files=>{core=files}}),keys:async()=>['vakantieapp-v1','whatsup-dog:https://example.test/other/:v1','whatsup-dog:https://example.test/whatsup-dog/:v1'],delete:async k=>deleted.push(k)}};
vm.runInNewContext(read('sw.js'),context);
let pending;
events.install({waitUntil:p=>pending=p});await pending;
for(const file of core){const clean=file.split('?')[0];assert.ok(clean==='./'||fs.existsSync(clean),'Missing precache '+file);}
assert.ok(core.includes(`./report-lifecycle.js?v=${version}`),'Report lifecycle is not precached with the release version');
events.activate({waitUntil:p=>pending=p});await pending;
assert.deepEqual(deleted,['whatsup-dog:https://example.test/whatsup-dog/:v1']);

const config={window:{},document:{querySelector:()=>true,createElement:()=>({dataset:{}}),body:{appendChild:()=>{}}}};
vm.runInNewContext(read('backend-config.js'),config);
assert.ok(!String(config.window.WHATSUP_DOG_BACKEND.publishableKey).startsWith('sb_secret_'));
if(config.window.WHATSUP_DOG_BACKEND.publishableKey.startsWith('eyJ'))assert.equal(JSON.parse(Buffer.from(config.window.WHATSUP_DOG_BACKEND.publishableKey.split('.')[1],'base64url')).role,'anon');
for(const tag of indexSource.matchAll(/(?:src|href)="([^"#]+)"/g)){if(!/^https?:/.test(tag[1]))assert.ok(fs.existsSync(tag[1].split('?')[0]),'Missing HTML asset '+tag[1]);}
console.log(`PASS: JavaScript, PWA assets, breed catalog (${breedCatalog.length}), enhanced reporting, persistent report lifecycle, production recovery migration, community wiring, cache isolation, public config, 20 Nijkerk polygons`);
